### ISSUE TITLE
Using yii alias in dsn is not resolved - can't open database

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/db-sqlite#65]
After cloning yii-app and adding yiisoft/db-sqlite I wanted to play with the migrations. But didn't work due to the error - can't open database. After a couple of time for debugging I figured out, that the alias won't work:/

### What steps will reproduce the problem?
'yiisoft/aliases' => [
        'aliases' => [
            '@root' => dirname(__DIR__),
            '@assets' => '@root/public/assets',
            '@assetsUrl' => '@baseUrl/assets',
            '@npm' => '@root/node_modules',
            '@public' => '@root/public',
            '@resources' => '@root/resources',
            '@runtime' => '@root/runtime',
            '@views' => '@root/resources/views',
            '@message' => '@root/resources/message',
        ],
    ],

    'yiisoft/db-sqlite' => [
        // working! 'dsn' => 'sqlite:'. dirname(__DIR__) .'/runtime/data/tropfendb.db',
        'dsn' => 'sqlite:@runtime/data/tropfendb.db', //not working
    ],

run vendor/bin/yii database/list

### What is the expected result?

List of current tables in the database.

### What do you get instead?

unable to open database file

### Additional info

| Q                | A
| ---------------- | ---
| Version          | DEV
| PHP version      |  8.0.0
| Operating system | Ubuntu

**Comment by samdark** [comment]
Currently you have to resolve alias yourself *before* passing it to connection instance.

**Comment by darkdef** [comment]
Dsn string cannot contain alias - only direct path
